Erster Entwurf `double_spaces_linter()`
INWT/INWTUtils pull request #17
Opened 2024-05-03 10:18 UTC by freimanninwt

Ich habe mal ein bisschen kommentiert und davor noch etwas gekürzt. Den Teil der Lint Location Korrektur habe ich auskommentiert. Habe aber trotzdem hingeschrieben, was das macht.

2024-05-09 11:26 UTC, miraKlein requested changes
Wow, das war echt ein gutes Stück Arbeit. Selbst beim Review war es noch kompliziert, trotz der Kommentare und der bisherigen Calls.
Ich hab jede Menge Vorschläge gemacht, wie sich der Code noch schöner schreiben lässt. Es sind viele kleine Sachen, aber keine ganz große Umstrukturierung :+1: 
Lass uns gern über meine Kommentare sprechen, falls etwas nicht sofort verständlich ist - ich hab ja selbst gerade noch Knoten im Hirn :)

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +            char_before <- if (start_pos > 1) substr(text, start_pos - 1, start_pos - 1) else ""
```suggestion
            char_before <- ifelse((start_pos > 1), substr(text, start_pos - 1, start_pos - 1), "")
```
Die Zeile darunter analog

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +            # First condition to flag general invalid patterns.
Kannst du hier beschreiben, warum dieser Double Space dann verboten ist? Sowas wie "double spaces after # are allowed because it could be an indented line commented out" und "double spaces before # are allowed and often used in headers" oder so

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +              has_invalid_match <- FALSE  # This sets the match back to false if it meets the specific criteria
Schreib doch hier die "specific criteria" konkret hin :)

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +            # Break early if an invalid match is found.
Warum eigentlich?
Wäre es auch möglich, alle invalid matches zu identifizieren nacheinander? Damit man eben nicht abbricht, sobald ein Lin gefunden wurde?
Das ist jetzt eine offene Frage - vielleicht ist das auch megakompliziert und wir lassen es lieber sein.

2024-05-09 11:26 UTC, miraKlein commented on tests/testthat/test-03_additionalLinters.R
> +  expect_true(length(lint_results) == 13, "Linter should detect 13 lints.")
Mit `lapply(lint_results, function(x) x$line_number)` kannst du zusätzlich noch checken, ob auch die richtigen Zeilen gefunden werden.

Aktuell sind manche Zeilen mehrfach drin, andere nicht. In den betroffenen Zeilen sind tatsächlich mehrere Lints, also richtig so. Dass manchmal nur ein Eintrag für eine Zeile vorkommt, obwohl mehrere Lints drin sind, könnte an dem `break` liegen, das ich auch kommentiert habe.
Ich wäre hier auch zufrieden, das `set` der Zeilennummern zu untersuchen (und das set sollte genau 3:13 enthalten).
Dass mehrere droppelte Leerzeichen in einer Zeile sind, kommt ja in der Praxis selten vor. Und dann ist es zu verschmerzen, wenn man den Linter eben zweimal laufen lassen muss.

2024-05-09 11:26 UTC, miraKlein commented on .Rbuildignore
> +^tmp$
Ich glaube, dass die beiden Einträge wieder raus können und die beiden Dateien nur Artefakte eines fehlgeschlagenen Tests sind.

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +    filter_comment_nodes_with_prior_code <- function(comment_nodes, code_nodes) {
Hier auch: Die Funktion besser außerhalb der anderen Funktion definieren und nach unten schieben.

Es wäre auch zu überlegen, ob der double-space-Linter eine eigene Datei verdient hat, so viel Code wie das ist. Aber bitte ganz am Ende, sonst erkennen wir nichts mehr in der Diff ;)

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +      for (i in seq_along(comment_nodes)) {
Auch hier könntest du direkt über die comment_nodes loopen statt über den Index.

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +    # that have `code_on_same_line` and then compares the amount of spaces
```suggestion
    # that have code and comments and then compares the amount of spaces
```

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +    # In the last part of the function we need to account for special cases like
Diesen Kommentar finde ich sehr hilfreich und gut verständlich!

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +        if (hash_pos > 0) {
Weiß heißt das inhaltlich? Vermutlich, dass die Zeile vor dem Kommentar Code enthält und nicht ausschließlich einen Kommentar? Aber... das wäre dann doch Position 1, also müsste es `> 1` heißen, sonst trifft es doch immer zu... offenbar hab ich's noch nicht verstanden.

2024-05-09 11:26 UTC, miraKlein commented on R/03_additionalLinters.R
> +          num_spaces_after_hash <- if (space_count_after_hash > 0) space_count_after_hash else nchar(substring_after_hash)
Hier bitte auch `ifelse` statt `if... else`

2024-05-10 09:44 UTC, freimanninwt commented on R/03_additionalLinters.R
> +    }
Das steht in Zusammenhang mit `xml <- source_expression$full_xml_parsed_content`. Würde es `source_expression$xml_parsed_content` heißen, sollte er das `level = "expression"` erwarten, weil hier einzelne `expression`, man könnte sagen `nodes`, untersucht werden. Das ist theoretisch der Default. Ich brauche aber die gesamte Liste `$full_xml_parsed_content`, weil die Logik bei mir etwas komplizierter ist und ich keinen Weg gefunden habe, beim Default zu bleiben. Deshalb erwarte ich hier das `level = file`.  Sollte das nicht so sein, hört er auf. Wenn du willst, kann ich dir das nochmal zeigen, man kann das manuell mit `get_source_expressions()` machen.

2024-05-10 09:46 UTC, freimanninwt commented on R/03_additionalLinters.R
> +    ### comment lints ###
Was genau meinst du mit extrahieren?

2024-05-10 10:02 UTC, freimanninwt commented on R/03_additionalLinters.R
> +    # nodes in the same `line1` value. F.e., we consider these three nodes: "(",
Hab ich hingeschrieben, einfach nur die Zeilennummer.

2024-05-10 13:50 UTC, miraKlein commented on R/03_additionalLinters.R
> +    ### comment lints ###
Einfach nur rausziehen. Also das, was du heute schon gemacht hast :)

2024-05-10 14:44 UTC, freimanninwt commented on R/03_additionalLinters.R
> +            # Break early if an invalid match is found.
hm.. habs mal rausgenommen und es macht gar keinen unterschied, was ich komisch finde, vmlt war es auf der falschen ebene und bringt gar nichts.. aktuell ist es so, dass lediglich ein lint pro lint-type (Comment, code, code before comment) je line angezeigt wird.. Der Vorteil ist, dass man nicht überschwemmt wird am Anfang, der Nachteil, dass man evtl zurückmuss.. denke, dass ich das nur dann hinkriege, wenn ich auch das problem mit der lint location gefixed bekomme, das hat evtl was miteinander zutun

2024-05-10 14:47 UTC, freimanninwt commented on tests/testthat/test-03_additionalLinters.R
> +  expect_true(length(lint_results) == 13, "Linter should detect 13 lints.")
genau, also dass dort mehrere lints drin liegen hat mit der art des lints zu tun. es wird nie mehr als 3 lints pro zeile geben, weil es stand jetzt drei arten gibt

2024-05-10 14:53 UTC, miraKlein commented on tests/testthat/test-03_additionalLinters.R
> +  expect_true(length(lint_results) == 13, "Linter should detect 13 lints.")
> ich kann den test so umschreiben, dass er das linenumber set checkt..

Ja, das wäre gut. Sonst ist er noch etwas schwammig und ließe sich überlisten ;)

Was den Fall "mehrere Lints pro Zeile" betrifft, lass und daran dann nichts mehr ändern. Das ist schon ok so. Wer so viele doppelte Leerzeichen in den Code _oder_ den Kommentar einbaut, darf bestraft werden ;)

2024-05-10 15:45 UTC, freimanninwt commented on R/03_additionalLinters.R
> +        if (hash_pos > 0) {
Ja du hast recht.. 

meine Denke war, dass wenn ich > 0 sage, alles, was nicht COMMENT ist (also STR_CONST) rauszuschmeißen. Denn dort gibt es kein "#" und der Start des nodes wäre bei 0. Bin das mit dem Browser() nochmal durchgegangen und die Logik später ist stark genug, um es dennoch rauszufiltern. also das hashpos > 0 brauche ich nicht, die hash_pos aber schon.

2024-05-13 08:11 UTC, miraKlein commented on R/03_additionalLinters.R
> +    ### code lints ###
```suggestion
    # Type 2: lints in code
```

2024-05-13 08:12 UTC, miraKlein commented on R/03_additionalLinters.R
> +    # The usual way of converting a node list into lints.
```suggestion
```

2024-05-13 08:12 UTC, miraKlein commented on R/03_additionalLinters.R
> +    # Lastly, we put all collected lints together.
```suggestion
    # Put collected lints of all three types together
```

2024-05-13 08:13 UTC, miraKlein commented on R/03_additionalLinters.R
> +    ### comment lints ###
Ich habe noch ein paar Vorschläge zu den Kommentaren gemacht. Einige Kommentare kann man meinem Empfinden nach jetzt kürzen, weil die Funktionsnamen schon für sich sprechen.

2024-05-13 08:15 UTC, miraKlein commented on R/03_additionalLinters.R
> +#' @title extractDoubleSpaceNodes
```suggestion
#' @title Extract nodes with incorrect double spaces
```

2024-05-13 08:15 UTC, miraKlein commented on R/03_additionalLinters.R
> +#' @title extractDoubleSpaceNodes
Der Titel soll schon beschreiben, was passiert, und nicht einfach der Funktionsname sein.

2024-05-13 08:16 UTC, miraKlein commented on R/03_additionalLinters.R
> +#' @export
Exportieren müssen wir diese Funktion nicht, weil sie nur intern von `double_space_linter` verwendet wird. Wir erwarten ja nicht, dass irgendwer sonst von INWT jemals `extract_double_space_nodes` direkt aufrufen möchte.

2024-05-13 08:19 UTC, miraKlein commented on R/03_additionalLinters.R
> +#' @description Inputs the node list above and collects the locations of the
"above" ist nicht so gut geeignet für die Doku, denn wenn man sich nur die Doku der Funktion anschaut, weiß man ja nicht, was darüber stand.

Außerdem: Bitte jedes Argument mit `@param` dokumentieren. Inhalt und Format des Output kann man, wenn man möchte, unter `@returns` dokumentieren. Unter `@description` ist dann noch Platz für weitere Infos zur Logik und Funktionsweise. Da könnte man hier vlt. die Ausnahmen zur "#" und "#'" beschreiben.

2024-05-13 08:19 UTC, miraKlein commented on R/03_additionalLinters.R
> +        # }
Memo: Falls sich herausstellt, dass wir das echt nicht brauchen, kann der Code gelöscht werden.

2024-05-13 08:20 UTC, miraKlein commented on R/03_additionalLinters.R
> +#' @title getCodeLints
```suggestion
#' @title Find lints in code
```

2024-05-13 08:21 UTC, miraKlein commented on R/03_additionalLinters.R
>  #' @export
```suggestion
```

2024-05-13 08:21 UTC, miraKlein commented on R/03_additionalLinters.R
> +#' @export
```suggestion
```

2024-05-13 08:22 UTC, miraKlein commented on R/03_additionalLinters.R
> +#' @title filterCommentNodesWithPriorCode
Auch hier anderen Titel als Funktionsnamen

2024-05-13 08:23 UTC, miraKlein commented on R/03_additionalLinters.R
> +    code_lines <- xml_attr(code_nodes, "line1")
Irgendwie ist das wieder verloren gegangen.

2024-05-13 08:25 UTC, miraKlein commented on R/03_additionalLinters.R
> +    for (line in unique_lines) {
Das war glaub ich die Stelle, wo das mit dem lapply doch nicht funktioniert, sondern eine Menge NULL-Einträge in die Ergebnisliste gepackt hat.

2024-05-13 08:25 UTC, miraKlein commented on R/03_additionalLinters.R
> +      for (i in seq_along(nodes)) {
Gemeinsam gelöst.

2024-05-13 12:39 UTC, miraKlein requested changes
Super, ganz viele Punkte sind ja jetzt schon gelöst. Ich hab sie mir schon angeschaut - hier noch ein paar Kommentare.

2024-05-15 06:47 UTC, freimanninwt commented on R/03_additionalLinters.R
> +    code_lines <- xml_attr(code_nodes, "line1")
Achso, ich hatte das in getCodeLints in die description gepackt (Zeile 131). Also es steht nicht explizit dahinter.

2024-05-15 08:32 UTC, freimanninwt commented
@miraKlein, habe direkt nach dem ersten Test auf einem Wahlprognose-Skript etwas bemerkt! Ich ruder' bzgl. des hash_pos > 0 in `get_comment_nodes_with_prior_code` zurück, bei dem ich meinte, es nicht brauchen zu müssen:
- wenn kein "#" vorhanden ist, aber trotzdem regexpr("#", text) ausgeführt wird, um die Position zu checken, gibt es den Default-Wert "-1" zurück. Die kleinstmögliche Position, wenn # vorhanden ist, ist natürlich 1. Jetzt weiß ich wieder, warum ich die if Restriktion reingenommen habe. 

![image](https://github.com/INWT/INWTUtils/assets/124151087/ae5baadc-a656-42b6-ac10-2e4594efaf1a)

- Das Problem hierbei ist eine Dopplung, denn Lines wie "x <- c("Hello     World")" geben einen Lint durch `extract_double_space_nodes` und durch `get_comment_nodes_with_prior_code`, weil die Restriktion beim letzteren weggenommen wurde.

- Ich würde es lösen, in dem ich `if (hash_pos =! -1) {}` schreibe und kurz kommentiere, warum.

2024-05-21 15:33 UTC, miraKlein commented on README.md
> +                              "function_argument_linter"),
Doch noch eine Sache: Die Readme wird in diesem Repo automatisch erzeugt. Sie speist sich aus doc/checkCodeStyle.Rmd.

Das heißt: Die Änderungen, die du hier gemacht hast, müssten noch in die doc/checkCodeStyle.Rmd übernommen werden. Hab ich auch nur gerade zufällig gesehen. Das war ja mal ganz ausgebufft, was wir uns damals überlegt haben.

2024-05-22 06:53 UTC, freimanninwt commented on tests/testthat/test-03_additionalLinters.R
> +  expect_contains(unlist(unique(lapply(lint_results, function(x) x$line_number))), 3:13)
Jap, die sind korrekt

2024-05-22 06:58 UTC, freimanninwt commented on README.md
> +                              "function_argument_linter"),
Du meinst `inst/checkCodeStyle.Rmd`? Ich glaube, da hatte ich es schon reingeschrieben..

2024-05-22 07:02 UTC, freimanninwt commented on README.md
> +                              "function_argument_linter"),
Also zumindest kann ich `args_no_default_first_linter` dort nicht finden

2024-05-22 07:32 UTC, miraKlein commented on README.md
> +                              "function_argument_linter"),
Du hast vollkommen Recht, ich hatte mein eigenes System nicht mehr ganz durchschaut, die Vignette ist die richtige Datei, um die Sachen zu ändern. Ich glaube, da fehlen noch zwei Stellen, aber ich würde das schnell auf meinem Branch machen (#21).

2024-05-22 07:34 UTC, miraKlein approved these changes

2024-05-22 07:35 UTC, merged